### ISSUE TITLE
버전 오류

### ISSUE THREAD

**Issue by MinecraftUserHAN1110** [1NTP/randomstn#3]
Discord.py-2.2.2에는 Option이 포함되지 않는다고 합니다.
Pycord 마찬가지로 Option이 포함되있지 않습니다.

**Comment by MinecraftUserHAN1110** [comment]
정정합니다.
Pycord와 Py-cord는 서로 다른 라이브러리이며 Py-cord에는 0.1.1 버전이 포함되있지 않습니다.

**Comment by 1NTP** [comment]
확인했고 수정예정입니다
